### ISSUE TITLE
Notification message port did not match the Kolibri server port.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri-installer-windows#104]
The Kolibri GUI notification url message did not match to the real Kolibri server port running. (Refer to the screenshot below)

This happened when I changed the default Kolibri server port using the `KOLIBRI_HTTP_PORT` environment variable

![Screen Shot 2019-06-25 at 2 53 25 PM](https://user-images.githubusercontent.com/8663934/60076322-dac8ff80-9759-11e9-9e97-d399fd229858.png)

**Comment by indirectlylit** [comment]
Looks like a follow-up from https://github.com/learningequality/kolibri-installer-windows/pull/80/files

**Comment by mrpau-richard** [comment]
Yeah I think it is, I assigned @mrpau-julius to work on this.

**Comment by mrpau-julius** [comment]
I found the reason for this issue on this [link](https://github.com/learningequality/kolibri-installer-windows/blob/develop/windows/gui-source/Kolibri/Kolibri.cpp#L229). the `ID_STRING_11_en` contains the caption of `Kolibri is now accessible locally at http://127.0.0.1:8080. Select Load in browser.`(you can check on this [link](https://github.com/learningequality/kolibri-installer-windows/blob/develop/windows/gui-source/Kolibri/Resource.rc#L87)). There is a function call [getKolibriLinkAddress()](https://github.com/learningequality/kolibri-installer-windows/blob/develop/windows/gui-source/Kolibri/Kolibri.cpp#L48) but data type is not match on the `sendTrayMessage parameter'.

The problem needs to convert the `char * to wchar_t` in order to match the data type in the `sendTrayMessage`.

**Comment by cpauya** [comment]
Fixed in https://github.com/learningequality/kolibri-installer-windows/pull/110
