### ISSUE TITLE
Remove the duplicated structure (and files) of the repo.

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri-installer-windows#105]
To remove the duplicated structure (and files) of the repo, let's do the following:

- [ ] Rename `windows/` folder to `src/`.
- [ ] Move or merge the following files at the root of the repo: `README.md`, `LICENSE`, `Makefile`, `make.bat`, `.gitignore`.
- [ ] Make sure the build servers are updated for the file structure change.

---
For reference, here are the text from the original filing of the issue.

> The code for this repo exists inside the `windows` folder.  This is a remnant of the previous structure from the [KA-Lite installers](https://github.com/learningequality/ka-lite-installers/) project.
>
> Because of this, we have duplicate: `README.md`, `LICENSE`, `.gitignore` files.  Maybe we can remove the `windows` folder and move it's contents in the root of the repo?
>
> Also, if we do remove the `windows` folder, we MUST make sure our build servers (and others) are updated to reflect this change.

**Comment by indirectlylit** [comment]
sounds good! adding to 1.3.2 milestone so we can wrap up 1.3.1 first

**Comment by benjaoming** [comment]
@cpauya I understand the intention, but could we perhaps keep the `windows/` folder (renaming it to `src/`?) and them not have the 5 said files in it (`README.md`, `LICENSE`, `Makefile`, `make.bat` and `.gitignore`).

I think that the duplicate structure should be avoided, but try to maintain the larger sub folder structure in `windows/` in a subfolder still, since it will make the root of this repository more complicated than, I would argue is reasonable :)

**Comment by cpauya** [comment]
Good idea @benjaoming! Will rename the issue title then.  I see two tasks so far:

1. Rename `windows` folder to `src`.
1. Move or merge the following files at the root of the repo: `README.md`, `LICENSE`, `Makefile`, `make.bat`, `.gitignore`.

**Comment by benjaoming** [comment]
Thanks @cpauya

**Comment by mrpau-richard** [comment]
fixed in #117  closing this.
