### ISSUE TITLE
Infinite "server is starting" notification

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri-installer-windows#113]
When I set the `KOLIBRI_HTTP_PORT` environment variable with non numeric characters and I run the Kolibri GUI, it will have an infinite `the server is starting` notification.

This also happened when a `port 8080` is occupied or not available.

**Comment by indirectlylit** [comment]
We actually see this scenario a lot, and users don't have any easy way to see what the underlying error is. The problem is actually very similar to #94 in that users don't get any information.

Can we detect when the Kolibri process exits with an error?

If so, we should detect that and switch from a transient "Server is starting" message to a Kolibri error message. Preferably, it would look something like:

> Kolibri encountered an error. Click to view logs.

Clicking the notification might launch the logs in `notepad.exe` or similar

**Comment by indirectlylit** [comment]
here are four examples of people running into this:

* https://community.learningequality.org/t/kolibri-error-message/868
* https://community.learningequality.org/t/my-kolibri-doesnt-startup-it-keeps-on-saying-the-server-is-starting-please-wait/1240
* https://community.learningequality.org/t/help-pls-kolibri-disconnecting-and-error-the-server-is-starting-please-wait/1054
* https://community.learningequality.org/t/kolibri-the-server-is-starting-please-wait-kolibri-exe/412
