### ISSUE TITLE
Unicode error when the installation wizard is in Spanish

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-installer-windows#122]
Reported by @jredrejo, when the OS is in Spanish, or the user selects Spanish as the language for the installation, possibly related to #34:

![image](https://user-images.githubusercontent.com/1457929/61895437-f539f880-af12-11e9-9162-c4862e544a4d.png)

cc @mrpau-richard @cpauya

**Comment by kollivier** [comment]
One possibility is that this is because the Languages translation files do not have the UTF-8 BOM. Sometimes the BOM is what apps use to distinguish between Unicode and ASCII text, so without it InnoSetup may be interpreting the language files as ASCII. This is just a theory, but the above issue does look like InnoSetup is not reading the translations in as Unicode.

**Comment by indirectlylit** [comment]
thanks - flagged @mrpau-dev in Slack https://learningequality.slack.com/archives/CAUTAU14Y/p1564087596013700

**Comment by cpauya** [comment]
We found the [source commit](https://github.com/learningequality/kolibri-installer-windows/commit/7c78d9e0bf99d027c08619aae438eb59b37d55af) for the "corrupted" `Languages\*.isl` files.  We think it's the settings in the VS Code editor used by @mrpau-julius under Windows during devt of the error logging feature a few months ago.  So sorry about these, thanks much for reporting the issue.

We've reverted those "corrupted" language files (and cherry-picked the needed changes) at https://github.com/learningequality/kolibri-installer-windows/pull/124.   

@radinamatic The Testing PR is at https://github.com/learningequality/kolibri/pull/5814 for testing the Windows installer being built.
