### ISSUE TITLE
migrate translation files to UTF-8

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-installer-windows#125]
We've had issues with encoding problems a couple times, e.g. #122, #34

Currently, our files are encoded using [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252) a.k.a. ISO-8859-1.

In order to standardize with the rest of our codebase and avoid encoding errors, we should switch to UTF-8.

See http://www.jrsoftware.org/ishelp/topic_unicode.htm

**Comment by cpauya** [comment]
Maybe there's an extension in VS Code to check encoding of Windows sources (specially the `Languages\*.isl` files)?  /cc: @mrpau-julius

**Comment by indirectlylit** [comment]
I don't think this is an editor configuration issue. From the Inno docs it says:

> Prior to Inno Setup 6 two versions of Inno Setup were available: Non Unicode Inno Setup and Unicode Inno Setup. Starting with Inno Setup 6 there's only one version available: Unicode Inno Setup.

We're using Inno Setup 5.5.9 Unicode. [According to this](https://stackoverflow.com/questions/40420445/how-to-edit-translate-an-inno-setup-isl-file) in version 5.x, to use unicode we need to use `*. islu` files instead of `*.isl`.

So I believe we either need to switch file extension or upgrade.

**Comment by cpauya** [comment]
Yup - we were already using the [unicode version (innosetup-5.5.9-unicode.exe) of InnoSetup 5.x](http://files.jrsoftware.org/is/5/) and our VS Code encoding already defaults to `UTF-8`.  

Using `*.islu` is very indicative - so yes, we must use `*.islu` as extension instead of `*.isl` for the project. 

Reference: [Is it safe to use .islu translation files in Inno Setup for all languages?](https://stackoverflow.com/questions/28449428/is-it-safe-to-use-islu-translation-files-in-inno-setup-for-all-languages)

**Comment by mrpau-julius** [comment]
I observe, there is an issue in VS Code encoding that cannot display the Unicode properly. 

Below you can see the behavior of VS Code encoding has a symbol of this character �, Notepad and Inno setup are display the language correctly.
![image](https://user-images.githubusercontent.com/38421180/62600625-eba48d80-b921-11e9-9d1d-6de8e8c8e92c.png)

After I save some changes in VS Code and open again in Notepad and Inno setup. The display language is incorrect.
![image](https://user-images.githubusercontent.com/38421180/62607344-83a97380-b930-11e9-9c58-839f1e2128bd.png)

I found out this existing [issue](https://github.com/Microsoft/vscode/issues/33720) on google that VS Code has an encoding problem.

**Comment by cpauya** [comment]
@mrpau-julius Ouch, good find!  Let's not use VSCode for the meantime and instead use SublimeText or the InnoSetup editor itself.

@indirectlylit Here's our over-all approach to this issue:

1. Convert language files from `*.isl` to `*.islu`.
1. Attempt to upgrade from InnoSetup 5.5.9 to latest [InnoSetup 6.0.2](http://www.jrsoftware.org/isdl.php#stable)
    * This requires that we change the contents of the ["\windows\inno-compiler\" folder](https://github.com/learningequality/kolibri-installer-windows/tree/develop/windows/inno-compiler) with the InnoSetup 6.0.2 compiler and libraries.
    * This requires testing also in Docker and in BuildKite if this approach works and doesn't break the build process.
    * If it takes a long time, we will create another issue specific to "Upgrade InnoSetup to latest 6.0.2 version".

**Comment by mrpau-julius** [comment]
@cpauya  I converted all the languages to `*.islu` and test it. I observe that the `Default.isl` can't convert to `*.islu`. I think the `Default.isl` must be in the standard extension.
![image](https://user-images.githubusercontent.com/38421180/62753283-88d80100-ba9d-11e9-8232-e67525fc9405.png)

I built successfully the installation and test in Windows 7. I check all the languages and found the `Greek language` is not translated properly.
![greek](https://user-images.githubusercontent.com/38421180/62753685-4283a180-ba9f-11e9-9558-bdeb1a734b7e.png)
 
I check my Code editor, this time I'm using Sublime Text 2. I found out in `Greek.islu`, the language was corrupted. Also, you see on Github develop repo in this link https://github.com/learningequality/kolibri-installer-windows/blob/develop/windows/inno-compiler/Languages/Greek.isl and try to compare it in [`v1.3.0`](https://github.com/learningequality/kolibri-installer-windows/blob/v1.3.0/windows/inno-compiler/Languages/Greek.isl)
Even I copy the Greek language on `v1.3.0` and paste it to my Code editor and built it again. The results are the same.

Now I proceed to the next part, upgrade the Inno setup to the latest version `6.0.2` to compare this can of issue.

**Comment by mrpau-julius** [comment]
I think the Inno setup 6, fix this issue by using the encoding type of `UTF-8 with BOM` but not the `UTF-8` only.
In above that I comment, the `Greek.isl` is corrupted. I tried to copy in `v1.3.0 tag repo` and paste it to my Code editor(Sublime text 2) and save it with encoding type `UTF-8 with BOM` and it works. 
![image](https://user-images.githubusercontent.com/38421180/62763781-f183a580-babe-11e9-839d-90879be95841.png)

And also we can standardize the extension to `*.isl` but make sure the encoding type is `UTF-8 with BOM`.

**Comment by mrpau-julius** [comment]
If the existing language is no longer in use, set language CodePage to 0. To detect the language’s file, there’s a special `*.islu` extension to use and can encode the file as Unicode. 

 I found out that the ‘LanguageCodePage’ is equivalent to ‘CodePage’. A code page is a character encoding and as such it is a specific association of a set of printable characters and controls characters with unique numbers. In our repository, we use the [Code page Identifier](https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers) [1252](https://github.com/learningequality/kolibri-installer-windows/blob/049f5b7d9d87f07043e2e8b1ab20522f1eabf6a3/windows/inno-compiler/Languages/Spanish.isl#L16), [1253](https://github.com/learningequality/kolibri-installer-windows/blob/049f5b7d9d87f07043e2e8b1ab20522f1eabf6a3/windows/inno-compiler/Languages/Greek.isl#L17) and [0](https://github.com/learningequality/kolibri-installer-windows/blob/049f5b7d9d87f07043e2e8b1ab20522f1eabf6a3/windows/inno-compiler/Languages/Nepali.islu#L17). `Nepali.islu` is using a code page value of 0, because it is not included in Microsoft Unicode. 

If I gather all the extension to `*.islu` it will become a Non Unicode. like, `Nepali.islu` that same as characters used when the installation is running. But the Greek language is a Unicode. So it must convert to display the correct characters.

This will happen if the Greek language extension has changed to `*.islu`.
![image](https://user-images.githubusercontent.com/38421180/63097409-32e3dd00-bf25-11e9-933e-41de1f2e81dc.png)

We must recommend to upgrade the Inno setup due to the latest version supporting both [Unicode and Non Unicode](http://www.jrsoftware.org/ishelp/index.php?topic=unicode). Using `*.isl it could have a uniform extension.
