### ISSUE TITLE
Windows installer appears to be incompatible with Windows 11

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri-installer-windows#202]
In Windows 11 it appears that Python gets installed into Program Files, rather than into the root drive \Python39 directory. This means that the InnoSetup configuration fails, as it is unable to find Python even though it has just installed it.

To resolve this, we would need to make sure that any references to Python in the InnoSetup file are not hardcoded to a specific directory but are based on the directory it is actually installed to.

In the simplest case, this may just mean conditionalizing the behaviour for Windows 11 to use a different hardcoded path.

**Comment by jamalex** [comment]
Some more context/details:

I already had Python 3.9 installed. It told me it needed to install again. I went through the full install process, then it went back to Kolibri’s installer saying “Ready to Install”, but when I clicked Install it AGAIN said it wasn’t installed (see below). Then I said Yes again, and it did a partial install (just recompiling core libs) and then finally proceeded to install Kolibri itself.

![image](https://user-images.githubusercontent.com/618416/225763382-1cb9de0d-e2ff-4eed-8fd3-23aeef288161.png)

It then errored out with:
![image](https://user-images.githubusercontent.com/618416/225763480-a4d55611-86ec-4f6c-8596-7e799e85ed36.png)

It then proceeded to uninstall Kolibri and ask me if I wanted to delete all my dat

I managed to get through the process by manually copying the Python39 folder from **C:\Program Files** into **C:\.** and starting over. It still asked me to install Python 3.9, but then proceeded to complete successfully and run.

When I then deleted C:\Python39, and started Kolibri... I got:
![image](https://user-images.githubusercontent.com/618416/225763676-3c9ea692-e968-48ce-87ca-e141b931735e.png)

**Comment by jamalex** [comment]
> In the simplest case, this may just mean conditionalizing the behaviour for Windows 11 to use a different hardcoded path.

Python seems to now add itself to the path automatically, so a decent option would be to just use the version that's on the path, and maybe look to **C:\Python39** and **C:\Program Files\Python39** as fallbacks.

It's worth noting that the original message says "Python 3.9+" is required, so we probably also shouldn't be hardcoding Python 3.9, if 3.10/3.11 will work as well.

**Comment by pcenov** [comment]
Some additional observations, hoping they will be of use:

1. Installing Kolibri 0.16.0a9 on both Windows 11 and 10 is working correctly when there is no previous installation of Kolibri and Python on the PC and the user is starting from scratch. In my case I am prompted to install Python 3.6.8 which gets installed in C:\Python36 by default without giving me any options to change that.
2. Upgrading Kolibri on both Windows 11 and 10 after having installed it in the way specified in point 1 is also working correctly - I am not being prompted to install Python so in that case the installer is able to recognize that Python has already been installed.
3. If I uninstall Kolibri and attempt to install it again - it then prompts me to install Python 3.6+ while the 3.6.8 version is still being installed on my PC and I haven't modified it in any way. So in that case the user can either agree to install Python again in which case the installation proceeds correctly or can stop the installation and get in the scenarios described above.

**Comment by jredrejo** [comment]
After doing some tests I can only confirm the diagnostic from @pcenov , the three cases he explains in his comment are exactly like that. I'd only add one more point:
- When installing and uninstalling 0.15 & 0.16 in the machine, there are remains of both python 3.6 & 3.9. These remains confuse the system, and after installing any version of kolibri, trying to start it again always provides a message saying that `.kolibri `folder has to be created, but it never reaches the point to create it.

It seems problems come not from the kolibri installer itself, but from the way python is installed because its uninstallation is not done correctly.

**Comment by jamalex** [comment]
I'm still experiencing this same issue with the latest installer (kolibri-0.16.0b0-signed.exe).

> that only happens when Python installations are mixed

This seems to be the likely cause for my case. I already had other versions of Python installed (3.6 and 3.9). We should make sure the installation is robust to existing versions of Python being installed (particularly since there is no indication to the user that this would be an issue, just confusing error messages).

It sounds like this may be sufficient to replicate the issue:
- In a fresh Windows 11 machine, manually install Python 3.6 and/or Python 3.9 (unclear which is the trigger)
- Install Kolibri using Windows installer

----------------
FURTHER DETAILS

<img width="533" alt="image" src="https://github.com/learningequality/kolibri-installer-windows/assets/618416/3d3f6819-e2d0-4fb4-b3f3-9a0c5324a769">

I then let it install Python 3.8 and it did that process slowly and then popped up that same modal again.

Did that twice more, and eventually made it a bit further along, but then got this:

<img width="524" alt="image" src="https://github.com/learningequality/kolibri-installer-windows/assets/618416/fe02526d-f362-4840-a1b3-6d14e7859ad6">

The path to the log file in that modal can neither be clicked nor selected to copy paste. Navigating to it in Explorer was unsuccessful as well (that folder is a redirect to C:\Users\jamal\OneDrive\Desktop). Neither the folder nor the file seem to exist.

Python 3.8 does seem to exist under C:\Python38 (and can be run), but there’s no pip in the script folder:

<img width="528" alt="image" src="https://github.com/learningequality/kolibri-installer-windows/assets/618416/22414f3d-7367-4460-bd50-d5791fa0f330">

So I can’t just directly run “pip” using Python 3.8, but it does seem it can be run using the module method:

<img width="533" alt="image" src="https://github.com/learningequality/kolibri-installer-windows/assets/618416/11fa8b6c-1324-4bfe-97b9-76fc36a23c16">

From the path shown there for where it’s using pip from, it seems like maybe the C:\Python38 folder just has some key executable files, but that the actual installation is in an AppData folder?

**Comment by jamalex** [comment]
It seems plausible that it is caused by remnants in the C:\Users\jamal\AppData\Roaming\Python folder, as well -- I will look further into that.

**Comment by jredrejo** [comment]
> It seems plausible that it is caused by remnants in the C:\Users\jamal\AppData\Roaming\Python folder, as well -- I will look further into that.

@jamalex did you do any other test?
Also, in order to have a better trazability and QA,  I think it's probably better to open a new issue for this problem as it does not seem to have any relation with Windows 11, it should be happening in any Windows version. Problems with the installer in Windows 11 have been fixed in #208

**Comment by rtibbles** [comment]
Extensive testing of #208 and #218 suggest that this issue is now resolved.
