### ISSUE TITLE
Windows Installer server not starting

### ISSUE THREAD

**Issue by jayoshih** [learningequality/kolibri-installer-windows#37]
After installing  [this installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMYkVMWFBLbjhva2M), I just keep getting "server is starting" notification 
![image](https://user-images.githubusercontent.com/7447496/30720224-77079db2-9edb-11e7-9e84-9cf5e8c25c1c.png)

I also tried [this installer](https://learningequality.slack.com/files/U0UAHMQP8/F77RSGW4E/kolibrisetup-0.6.dev020170921163803_git.exe) and that just shows all of the interactions as being disabled 
![image](https://user-images.githubusercontent.com/7447496/30720291-afe16c1c-9edb-11e7-8b1e-2c268398ff39.png)

OS: Windows 10

**Comment by mrpau-richard** [comment]
Hi @jayoshih can you try to manually run the kolibri in the command prompt using this command.
`C:\Python27\Scripts\kolibri.exe start`
Can you also post the output logs here if you encountered an error.

**Comment by laurenlichtman** [comment]
I ran into the same issue on installation but when I didn't touch any of the installation windows for a few minutes, the server did start in the background and I was able to click "Load in browser." The window with the IP and port to run Kolibri did not appear. I had Kolibri v0.5.x already installed on my Windows10 machine so that could also be the difference.

**Comment by indirectlylit** [comment]
we haven't seen this in a long time - closing
